document.write("<"+"script type=\"text/javascript\"><"+"!--\n");
document.write("google_ad_client = \"ca-pub-5741694739418833\";\n");
document.write("/* 728 x 90 In Posts */\n");
document.write("google_ad_slot = \"5263081508\";\n");
document.write("google_ad_width = 728;\n");
document.write("google_ad_height = 90;\n");
document.write("//-->\n");
document.write("<"+"/script>\n");
document.write("<"+"script type=\"text/javascript\"\n");
document.write("src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n");
document.write("<"+"/script>");
